name: Build Arch ISO with SysInstaller Commit

on:
  push:
    branches:
      - master
  pull_request:
    paths-ignore:
      - '**.gitignore'
      - '**.md'
      - 'LICENSE'
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
      options: --privileged
    steps:
      - uses: actions/checkout@v2
      - run: pwd
      - run: find .
      - run: cat /etc/os-release
      - run: pacman -Sy; pacman --noconfirm -S git archiso
      - run: cp -r /usr/share/archiso/configs/releng /tmp/archlive
      - run: mkdir -p /tmp/archlive/airootfs/root/SysInstaller; cp -r . /tmp/archlive/airootfs/root/SysInstaller
      - run: find /tmp/archlive/airootfs/root/SysInstaller/data /tmp/archlive/airootfs/root/SysInstaller/main.sh -type f | xargs chmod +x
      - run: echo "echo Type 'install' to launch the installer" >> /tmp/archlive/airootfs/root/.zprofile
      - run: echo "alias install='cd ~/SysInstaller && ./main.sh'" >> /tmp/archlive/airootfs/root/.zprofile
      - run: cat /tmp/archlive/airootfs/root/.zprofile
      - run: echo -e "git" >> /tmp/archlive/packages.x86_64
      - run: find /tmp/archlive
      - run: cd /tmp/archlive;  mkarchiso -v -w work/ -o out/ ./
      - uses: actions/upload-artifact@v2
        with:
          name: Arch Live ISO
          path: /tmp/archlive/out/*.iso
